/**
 * PV3 Beat 1 v2 — placement fixes + token loudness
 * Changes from v1:
 *   - River cue moved to pos 1 (after hook line, before "I came because...")
 *   - "A brass token..." line split at the SFX point (new segments 10, 12)
 *   - Token cue normalized to -10 LUFS before pre-populating slot 11
 *   - All unchanged voice segments pre-populated by copying existing audio
 *   - generate-voices generates only segments 10 and 12
 *   - Zero SFX generated by pipeline
 */
import { readFileSync, writeFileSync, unlinkSync } from 'fs'
import { execFile } from 'child_process'
import { promisify } from 'util'
import { join } from 'path'
import { tmpdir } from 'os'
import crypto from 'crypto'

const execFA = promisify(execFile)
const env = readFileSync('.env.local', 'utf8')
const getE = k => { const m = env.match(new RegExp(k + '="([^"]+)"')); return m ? m[1] : null }
const SB  = getE('NEXT_PUBLIC_SUPABASE_URL')
const KEY = ***'SUPABASE_SERVICE_ROLE_KEY')
const EL  = getE('ELEVENLABS_API_KEY')
const APP = 'https://app.endless-tales.com'
const B1  = 'a37fdc46-24d0-49a7-b749-320076978c3b'
const PUB = `${SB}/storage/v1/object/public/audio`
const SFX_SERIES = `${PUB}/asc3/series/bell-beneath-falls-park/sfx`

const sha256 = buf => crypto.createHash('sha256').update(buf).digest('hex')
const log = m => console.log(`[B1v2] ${m}`)
const fail = m => { throw new Error(`FATAL: ${m}`) }

const SERIES_HASHES = {
  'river-roar': '58d9d420f24fcc577ed14a5024f373de5386c09eb6ac6632a816b3dd65d6f046',
  'token-a':    '049245ffea20c1532aa84af6144c50286747bb515f795e5ef1f2fd88c1bf1807',
}

async function dl(url) {
  const r = await fetch(url)
  if (!r.ok) throw new Error(`dl ${url}: ${r.status}`)
  return Buffer.from(await r.arrayBuffer())
}

async function dlMaybe(url) {
  const r = await fetch(url)
  if (!r.ok) return null
  return Buffer.from(await r.arrayBuffer())
}

async function up(storagePath, buf) {
  const r = await fetch(`${SB}/storage/v1/object/audio/${storagePath}`, {
    method: 'PUT',
    headers: { Authorization: `Bearer ${KEY}`, 'Content-Type': 'audio/mpeg', 'x-upsert': 'true' },
    body: buf
  })
  if (!r.ok) throw new Error(`up ${storagePath}: ${r.status} ${await r.text()}`)
}

async function silenceMp3(secs) {
  const tmp = join(tmpdir(), `sil_${Date.now()}.mp3`)
  await execFA('ffmpeg', ['-f','lavfi','-i','anullsrc=r=44100:cl=stereo',
    '-t', String(secs), '-ar','44100','-ac','2','-b:a','128k','-y', tmp], { stdio:'pipe' })
  const buf = readFileSync(tmp); try { unlinkSync(tmp) } catch {}
  return buf
}

async function measuredDuration(buf) {
  const tmp = join(tmpdir(), `dur_${Date.now()}.mp3`)
  writeFileSync(tmp, buf)
  try {
    const { stdout } = await execFA('ffprobe', ['-v','quiet','-print_format','json','-show_format', tmp])
    return parseFloat(JSON.parse(stdout).format.duration)
  } finally { try { unlinkSync(tmp) } catch {} }
}

// Normalize to target LUFS using ffmpeg loudnorm
async function normLufs(buf, targetLufs) {
  const tmp = join(tmpdir(), `norm_${Date.now()}`)
  writeFileSync(`${tmp}_in.mp3`, buf)
  await execFA('ffmpeg', [
    '-i', `${tmp}_in.mp3`,
    '-af', `loudnorm=I=${targetLufs}:TP=-1.5:LRA=11`,
    '-ar', '44100', '-ac', '2', '-b:a', '192k',
    '-y', `${tmp}_out.mp3`
  ], { stdio: 'pipe' })
  const out = readFileSync(`${tmp}_out.mp3`)
  try { unlinkSync(`${tmp}_in.mp3`); unlinkSync(`${tmp}_out.mp3`) } catch {}
  return out
}

async function genVoice(text, voiceId, settings = { stability:0.5, similarity_boost:0.75, style:0.0, use_speaker_boost:true }) {
  const r = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`, {
    method: 'POST',
    headers: { 'xi-api-key': EL, 'Content-Type': 'application/json' },
    body: JSON.stringify({ text, model_id: 'eleven_multilingual_v2', voice_settings: settings })
  })
  if (!r.ok) throw new Error(`TTS: ${r.status} ${await r.text()}`)
  return Buffer.from(await r.arrayBuffer())
}

const MARA_VOICE = 'ovUpRQCoNYADjai0c9kP'

// ── 1. Update Beat 1 script in DB ────────────────────────────────────────────
log('1. Updating Beat 1 script (river move + token line split)...')

const NEW_SCRIPT = `TITLE: The Bell Beneath Falls Park — Promo (PV3 Beat 1)
SERIES: The Bell Beneath Falls Park
EPISODE: PV3-B1
VARIANT: LANDING-STORY-001
NARRATOR: Mara Vance

CHARACTER GUIDE
---
MARA — female, middle_aged, american, calm — Mara Vance narrates her own story from within it. First-person protagonist.
ELI — male, middle_aged, american, calm — Eli Mercer. Local historian. Scholarly, measured, observant.
LENA — female, middle_aged, american, serious — Detective Lena Ortiz. Authoritative, clipped, guarded.
---

[START AUDIO DRAMA SCRIPT]

MARA: In Greenville, the Reedy River keeps its secrets beneath Falls Park, especially after dark.

[SFX: REEDY RIVER RUSHING BENEATH LIBERTY BRIDGE]

MARA: I came because Eli Mercer sent me a photograph of a dead man lying under Liberty Bridge. The man's name was Adrian Cross. Greenville Police had already sealed the riverwalk, but Eli knew a maintenance path that ran behind the old stone wall.

ELI: Mara, stay close to me. Detective Lena posted officers at both ends of the bridge, and she will arrest us before she hears your explanation.

MARA: Eli guided me beneath Liberty Bridge, where floodwater had left branches against the concrete supports. Adrian Cross lay beyond the police tape, one hand closed around something metallic.

LENA: Mara Vance, step away from the body. You are contaminating an active crime scene.

MARA: Detective Lena came down the path with her flashlight raised. I showed her the message Eli had received from Adrian Cross three hours before his death.

MARA: The message said, "Tell Claire's daughter the bell was never in the church."

LENA: Claire Vance disappeared twelve years ago. Why would Adrian Cross mention your mother tonight?

MARA: I knelt beside Adrian's closed hand.

MARA: A brass token slipped free and rang once against the river rock.

[SFX: SMALL METAL OBJECT STRIKING STONE]

MARA: It was stamped with a tiny bell.

ELI: Mara, your mother had one exactly like it.`

const r_patch = await fetch(`${SB}/rest/v1/stories?id=eq.${B1}`, {
  method: 'PATCH',
  headers: { apikey: KEY, Authorization: `Bearer ${KEY}`, 'Content-Type': 'application/json', Prefer: 'return=minimal' },
  body: JSON.stringify({ script: NEW_SCRIPT })
})
log(`   Script PATCH: HTTP ${r_patch.status}`)
// Verify
const r_verify = await fetch(`${SB}/rest/v1/stories?id=eq.${B1}&select=script`, {
  headers: { apikey: KEY, Authorization: `Bearer ${KEY}` }
})
const script_check = (await r_verify.json())[0].script
const hasRiverEarly = script_check.includes('"especially after dark."\n\n[SFX: REEDY RIVER')
const hasSplit = script_check.includes('river rock.\n\n[SFX: SMALL METAL OBJECT') && script_check.includes('a tiny bell.')
const hasOldPos = script_check.includes('[SFX: SMALL METAL OBJECT STRIKING STONE]\n\nMARA: A brass token')
log(`   river_early=${hasRiverEarly} token_split=${hasSplit} old_position_removed=${!hasOldPos}`)
if (!hasRiverEarly || !hasSplit || hasOldPos) fail('Script update verification failed')

// ── 2. Load series cues ───────────────────────────────────────────────────────
log('2. Loading series cues...')
const riverBuf = await dl(`${SFX_SERIES}/river-roar.mp3`)
const tokenRaw = await dl(`${SFX_SERIES}/token-a.mp3`)
if (sha256(riverBuf) !== SERIES_HASHES['river-roar']) fail('river-roar series hash mismatch')
if (sha256(tokenRaw) !== SERIES_HASHES['token-a']) fail('token-a series hash mismatch')
log(`   river-roar: ${riverBuf.length}B ✓`)
log(`   token-a raw: ${tokenRaw.length}B ✓`)

// ── 3. Normalize token to -10 LUFS (err loud) ────────────────────────────────
log('3. Normalizing token-a to -10 LUFS...')
const tokenLoud = await normLufs(tokenRaw, -10)
const tokenLoudHash = sha256(tokenLoud)
const tokenDur = await measuredDuration(tokenLoud)
log(`   token-a normalized: ${tokenLoud.length}B duration=${tokenDur.toFixed(2)}s sha256=${tokenLoudHash.slice(0,16)}...`)
log(`   (series token-a sha256=${SERIES_HASHES['token-a'].slice(0,16)}... — different because normalized)`)

// ── 4. Fetch existing Beat 1 segments for reuse ───────────────────────────────
log('4. Fetching existing Beat 1 voice segments for reuse...')
const seg = {}
const toFetch = [0, 1, 3, 4, 5, 6, 7, 8, 9, 12]
for (const n of toFetch) {
  const pad = String(n).padStart(4, '0')
  const url = `${PUB}/asc3/${B1}/segment_${pad}.mp3`
  const buf = await dlMaybe(url)
  if (buf) {
    seg[n] = buf
    log(`   segment_${pad}: ${buf.length}B ✓`)
  } else {
    log(`   segment_${pad}: NOT FOUND (will be generated by pipeline)`)
  }
}

// ── 5. Pre-populate ALL slots ─────────────────────────────────────────────────
log('5. Pre-populating all Beat 1 slots...')
const cueLog = []

// segment_0000: unchanged (pos 0 same)
if (seg[0]) {
  await up(`asc3/${B1}/segment_0000.mp3`, seg[0])
  cueLog.push('segment_0000 MARA "In Greenville...": REUSED (existing, unchanged position)')
}

// sfx_0001: river (new position — was sfx_0002)
await up(`asc3/${B1}/sfx_0001.mp3`, riverBuf)
cueLog.push(`sfx_0001 [RIVER]: REUSED series/river-roar.mp3 sha256=${SERIES_HASHES['river-roar'].slice(0,16)}...`)
log(`   sfx_0001 river: ${riverBuf.length}B (~${(riverBuf.length/16000).toFixed(1)}s)`)

// segment_0002: "I came because..." (was segment_0001, same text)
if (seg[1]) {
  await up(`asc3/${B1}/segment_0002.mp3`, seg[1])
  cueLog.push('segment_0002 MARA "I came because...": REUSED (copied from old segment_0001, same text)')
}

// segments 0003-0009: same positions, reuse
for (const [old, newn] of [[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9]]) {
  if (seg[old]) {
    const pad = String(newn).padStart(4, '0')
    await up(`asc3/${B1}/segment_${pad}.mp3`, seg[old])
    cueLog.push(`segment_${pad}: REUSED (same position)`)
  }
}

// segment_0010: "A brass token slipped free and rang once against the river rock."
// → GENERATE via ElevenLabs (new split text)
log('   Generating segment_0010 (split half 1): "A brass token slipped free..."')
let s10 = await genVoice('A brass token slipped free and rang once against the river rock.', MARA_VOICE)
s10 = await normLufs(s10, -16)
await up(`asc3/${B1}/segment_0010.mp3`, s10)
cueLog.push('segment_0010 MARA "A brass token slipped free...": GENERATED (new split line)')
log(`   segment_0010: ${s10.length}B ✓`)

// sfx_0011: token-a normalized loud (new position — was sfx_0010)
await up(`asc3/${B1}/sfx_0011.mp3`, tokenLoud)
cueLog.push(`sfx_0011 [TOKEN]: series/token-a.mp3 normalized -10 LUFS sha256=${tokenLoudHash.slice(0,16)}...`)
log(`   sfx_0011 token: ${tokenLoud.length}B ✓`)

// segment_0012: "It was stamped with a tiny bell."
// → GENERATE via ElevenLabs (new split text)
log('   Generating segment_0012 (split half 2): "It was stamped with a tiny bell."')
let s12 = await genVoice('It was stamped with a tiny bell.', MARA_VOICE)
s12 = await normLufs(s12, -16)
await up(`asc3/${B1}/segment_0012.mp3`, s12)
cueLog.push('segment_0012 MARA "It was stamped with a tiny bell.": GENERATED (new split line)')
log(`   segment_0012: ${s12.length}B ✓`)

// segment_0013: ELI "Mara, your mother had one exactly like it." (was segment_0012, same text)
if (seg[12]) {
  await up(`asc3/${B1}/segment_0013.mp3`, seg[12])
  cueLog.push('segment_0013 ELI "Mara, your mother had one exactly like it.": REUSED (copied from old segment_0012)')
}

// Delete old wrong SFX slots (stale files that no longer correspond to script positions)
for (const old of ['sfx_0002', 'sfx_0010', 'segment_0001', 'segment_0011']) {
  await fetch(`${SB}/storage/v1/object/audio/asc3/${B1}/${old}.mp3`, {
    method: 'DELETE', headers: { Authorization: `Bearer ${KEY}` }
  })
}
log('   Deleted stale old-position files (sfx_0002, sfx_0010, segment_0001, segment_0011)')

// ── 6. Silent music bed ───────────────────────────────────────────────────────
log('6. Silent music bed...')
await up(`asc3/${B1}/background_music.mp3`, await silenceMp3(360))

// ── 7. generate-voices ────────────────────────────────────────────────────────
log('7. generate-voices (should find all slots pre-populated)...')
const gv = await fetch(`${APP}/api/admin/generate-voices`, {
  method: 'POST', headers: {'Content-Type':'application/json'},
  body: JSON.stringify({ storyId: B1 })
})
const gvb = await gv.json().catch(() => ({}))
log(`   HTTP ${gv.status} | succeeded=${gvb?.succeeded||'?'} failures=${(gvb?.failures||[]).length}`)
if (!gv.ok) fail(`generate-voices: ${gv.status} ${JSON.stringify(gvb).slice(0,300)}`)
if ((gvb?.failures||[]).length) log(`   ⚠ Failures: ${gvb.failures.map(f=>f.segment).join(', ')}`)

// ── 8. Verify SFX slots post-generate-voices ──────────────────────────────────
log('8. Verifying SFX slots post-generate-voices...')
const postRiver = await dl(`${PUB}/asc3/${B1}/sfx_0001.mp3`)
const postToken = await dl(`${PUB}/asc3/${B1}/sfx_0011.mp3`)
const postRiverHash = sha256(postRiver)
const postTokenHash = sha256(postToken)
const riverOk = postRiverHash === SERIES_HASHES['river-roar']
const tokenOk = postTokenHash === tokenLoudHash
log(`   sfx_0001 river: ${postRiver.length}B sha256=${postRiverHash.slice(0,16)}... ${riverOk ? '✅ MATCH' : '❌ MISMATCH'}`)
log(`   sfx_0011 token: ${postToken.length}B sha256=${postTokenHash.slice(0,16)}... ${tokenOk ? '✅ MATCH (normalized)' : '❌ MISMATCH'}`)
if (!riverOk) fail('sfx_0001 was overwritten by generate-voices')
if (!tokenOk) fail('sfx_0011 was overwritten by generate-voices')

// ── 9. render-final-mix ───────────────────────────────────────────────────────
log('9. render-final-mix...')
const rfr = await fetch(`${APP}/api/asc3/render-final-mix`, {
  method: 'POST', headers: {'Content-Type':'application/json'},
  body: JSON.stringify({ storyId: B1 })
})
const rfrb = await rfr.json().catch(() => ({}))
log(`   HTTP ${rfr.status}`)
if (!rfr.ok || !rfrb?.success) fail(`render-final-mix: ${rfr.status} ${JSON.stringify(rfrb).slice(0,200)}`)
const b1Url = (rfrb?.finalAudioUrl || `${PUB}/asc3/${B1}/final_mix.mp3`).split('?')[0]
log(`   Mix: ${b1Url}`)

// ── 10. Measure ───────────────────────────────────────────────────────────────
log('10. Measuring Beat 1 runtime...')
const b1Buf = await dl(b1Url)
const b1Dur = await measuredDuration(b1Buf)
const b1Str = `${Math.floor(b1Dur/60)}m ${(b1Dur%60).toFixed(2)}s`
log(`   MEASURED: ${b1Dur.toFixed(3)}s (${b1Str})`)

const hr = await fetch(b1Url, { method: 'HEAD' })
log(`   Verify: HTTP ${hr.status} ${hr.ok ? '✓' : '✗'}`)

// ── Report ────────────────────────────────────────────────────────────────────
log('')
log('═══ BEAT 1 v2 COMPLETE ═══')
log(`\nURL: ${b1Url}`)
log(`Measured runtime: ${b1Dur.toFixed(3)}s (${b1Str})`)
log(`\nSFX sha256:`)
log(`  sfx_0001 river:  ${postRiverHash}  (series/river-roar.mp3, unchanged)`)
log(`  sfx_0011 token:  ${postTokenHash}  (series/token-a.mp3 normalized -10 LUFS)`)
log(`\nRiver cue duration: ~${(riverBuf.length/16000).toFixed(1)}s (locked PV2 cue, no trimming needed)`)
log(`\nPer-cue REUSED vs GENERATED:`)
for (const c of cueLog) log(`  ${c}`)
log(`\nVoice segments GENERATED: 2 (segment_0010 + segment_0012 — split lines only)`)
log(`SFX GENERATED by pipeline: 0 ✓`)
log(`\ncomplete_story_package: will fail (HOOK-GATE — expected)`)
log('PV1 + PV2 + Beat 2: untouched.')
