export default function PrivacyPolicy() {
  return (
    <div style={{ minHeight: "100vh", background: "#0a0a0f", color: "white", fontFamily: "system-ui, sans-serif" }}>
      <div style={{ maxWidth: "720px", margin: "0 auto", padding: "48px 24px 80px" }}>
        <div style={{ marginBottom: "48px" }}>
          <a href="/" style={{ color: "#f0a030", fontSize: "14px", fontWeight: 600, textDecoration: "none", marginBottom: "32px", display: "block" }}>← Back to Endless Tales</a>
          <h1 style={{ fontSize: "36px", fontWeight: 900, marginBottom: "8px" }}>Privacy Policy</h1>
          <p style={{ color: "rgba(255,255,255,0.4)", fontSize: "14px" }}>Last updated: March 27, 2026</p>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: "40px" }}>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>1. Introduction</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>Wonder Books Press operates Endless Tales at app.endless-tales.com. This Privacy Policy explains how we collect, use, and protect your personal information.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>2. Information We Collect</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}><strong style={{ color: "white" }}>You provide:</strong> name, email, payment info (via Stripe), referral codes, and story reviews. <strong style={{ color: "white" }}>Collected automatically:</strong> playback progress, listening history, library activity, device/browser info, and general location.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>3. How We Use Your Information</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>To provide and improve the Service, process payments, personalize your experience, send transactional and promotional emails (opt-out anytime), and detect fraud.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>4. Third-Party Services</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>We use <strong style={{ color: "white" }}>Supabase</strong> (database/auth), <strong style={{ color: "white" }}>Stripe</strong> (payments), <strong style={{ color: "white" }}>ElevenLabs</strong> (AI voice — your first name may be used for personalized audio greetings), <strong style={{ color: "white" }}>Vercel</strong> (hosting), and <strong style={{ color: "white" }}>Resend</strong> (email). We do not sell your personal information.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>5. Data Retention</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>Data is retained while your account is active. Upon deletion, personal data is removed within 30 days except where required for legal or financial compliance.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>6. Your Rights</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>You may access, correct, or delete your data and opt out of marketing emails at any time. Contact <a href="mailto:hello@endless-tales.com" style={{ color: "#f0a030", textDecoration: "none" }}>hello@endless-tales.com</a>.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>7. Cookies and Local Storage</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>We use local storage for playback progress, guest history, and playlists. We use cookies for authentication sessions. No third-party advertising cookies.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>8. Children&apos;s Privacy</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>The Service is not directed to children under 13. We do not knowingly collect data from children under 13.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>9. Security</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>We use HTTPS, Supabase authentication, and database access controls to protect your data.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>10. Changes to This Policy</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>We may update this policy and will notify you of significant changes by email or in-app notice.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>11. Contact</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>Questions? <a href="mailto:hello@endless-tales.com" style={{ color: "#f0a030", textDecoration: "none" }}>hello@endless-tales.com</a> — Wonder Books Press, Elloree, SC</p></section>
        </div>
      </div>
    </div>
  )
}
