export default function TermsOfService() {
  return (
    <div style={{ minHeight: "100vh", background: "#0a0a0f", color: "white", fontFamily: "system-ui, sans-serif" }}>
      <div style={{ maxWidth: "720px", margin: "0 auto", padding: "48px 24px 80px" }}>
        <div style={{ marginBottom: "48px" }}>
          <a href="/" style={{ color: "#f0a030", fontSize: "14px", fontWeight: 600, textDecoration: "none", marginBottom: "32px", display: "block" }}>← Back to Endless Tales</a>
          <h1 style={{ fontSize: "36px", fontWeight: 900, marginBottom: "8px" }}>Terms of Service</h1>
          <p style={{ color: "rgba(255,255,255,0.4)", fontSize: "14px" }}>Last updated: March 27, 2026</p>
        </div>
        <div style={{ display: "flex", flexDirection: "column", gap: "40px" }}>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>1. Acceptance of Terms</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>By accessing or using Endless Tales, operated by Wonder Books Press, you agree to be bound by these Terms of Service.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>2. Description of Service</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>Endless Tales is an audio storytelling platform providing subscribers access to a library of original audio dramas and stories for personal, non-commercial use only.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>3. Accounts and Registration</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>You must be at least 13 to create an account. You agree to provide accurate information, keep credentials secure, and be responsible for all activity under your account.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>4. Subscription and Billing</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>New subscribers receive a 14-day free trial. A valid credit card is required but not charged until the trial ends. Subscriptions renew monthly. Founding Member rates are locked for the life of an active subscription. Cancel anytime before the trial ends to avoid charges. Refunds are evaluated case-by-case within 14 days of a charge. Payments processed by Stripe — we do not store card details.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>5. Content and Intellectual Property</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>All content is the property of Wonder Books Press or its licensors. You receive a limited license to stream for personal use only. Downloading, reproducing, or distributing content is prohibited without written permission.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>6. Acceptable Use</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>You agree not to use the Service unlawfully, attempt unauthorized access, scrape content, share credentials, or interfere with the Service.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>7. AI-Generated Content</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>Some content is produced using AI tools including AI-generated voices, scripts, music, and cover art. All AI content is reviewed under the editorial oversight of Wonder Books Press.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>8. Disclaimers</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>The Service is provided as-is without warranties. We reserve the right to modify, suspend, or discontinue the Service at any time without notice.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>9. Limitation of Liability</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>Wonder Books Press is not liable for indirect or consequential damages. Total liability shall not exceed the amount you paid us in the three months preceding the claim.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>10. Governing Law</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>These terms are governed by the laws of the State of South Carolina. Disputes are subject to the exclusive jurisdiction of courts in South Carolina.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>11. Changes to Terms</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>We may update these terms at any time. Continued use after changes are posted constitutes acceptance.</p></section>
          <section><h2 style={{ fontSize: "20px", fontWeight: 800, color: "#f0a030", marginBottom: "12px" }}>12. Contact</h2><p style={{ color: "rgba(255,255,255,0.75)", lineHeight: 1.7, fontSize: "15px" }}>Questions? <a href="mailto:hello@endless-tales.com" style={{ color: "#f0a030", textDecoration: "none" }}>hello@endless-tales.com</a> — Wonder Books Press, Elloree, SC</p></section>
        </div>
      </div>
    </div>
  )
}
