// ATL-BELLE-CACHE-001 — Belle variant cache helpers.
//
// Belle intro/outro text variants are generated by a haiku LLM call in
// /api/admin/generate-belle-variants and stored in story_belle_variants.
// Package-race retries and circuit re-dispatches re-enter that route and
// previously regenerated ALL variants from scratch on every retry (74% of
// monthly API spend on Jul 10-11 2026).
//
// The cache key is a sha256 hash over everything that determines the LLM
// output: the fully-built prompt (which embeds the script/prose excerpts,
// title, series metadata, author, genre, description, series position, and
// the listener-name variant parameters baked into the prompt template), the
// model id, and an explicit prompt-template version. If the script or the
// template changes, the hash changes and variants regenerate. If nothing
// changed, a retry reuses the stored variants and skips the LLM call.

import { createHash } from 'crypto'

// Bump this to force regeneration of all Belle variants even when the
// prompt text is unchanged (e.g. model behavior change, validation change).
export const BELLE_VARIANT_PROMPT_VERSION = 'v1'

export type BelleVariantCacheRow = {
  kind: string
  variant_key: string
  script_hash?: string | null
}

/**
 * Compute the cache key (sha256 hex) for a Belle variant generation request.
 * The prompt already embeds every story-specific input (script excerpt,
 * prose excerpt, title, series position, author, genre, description) and the
 * template rules, so hashing prompt + model + version covers all inputs that
 * determine the output.
 */
export function computeBelleVariantCacheKey(input: {
  model: string
  prompt: string
  promptVersion?: string
}): string {
  const version = input.promptVersion ?? BELLE_VARIANT_PROMPT_VERSION
  return createHash('sha256')
    .update(JSON.stringify({ v: version, model: input.model, prompt: input.prompt }))
    .digest('hex')
}

/**
 * A cache hit requires:
 *  - every expected `kind:variant_key` combination is present in the stored
 *    rows (all 7 canonical variants), AND
 *  - every stored row carries the current script hash.
 * Rows written before the script_hash migration (script_hash NULL) or after
 * a script/template change (stale hash) are treated as a miss so variants
 * regenerate exactly once and are cached from then on.
 */
export function isBelleVariantCacheHit(
  rows: BelleVariantCacheRow[] | null | undefined,
  expectedKeys: string[],
  scriptHash: string,
): boolean {
  if (!Array.isArray(rows) || rows.length === 0) return false
  if (!scriptHash) return false
  const seen = new Set(rows.map((row) => `${row.kind}:${row.variant_key}`))
  if (!expectedKeys.every((key) => seen.has(key))) return false
  return rows.every((row) => row.script_hash === scriptHash)
}
