export type ServiceCategory =
  | 'Production'
  | 'Infrastructure'
  | 'Architecture'
  | 'Marketing'
  | 'Finance'
  | 'Analytics'
  | 'Legal / Compliance'

export type ServiceStatus = 'active' | 'paused' | 'pending_setup' | 'inactive' | 'cancelled'

export type BillingCycle = 'monthly' | 'annual' | 'usage' | 'none'

export type ServiceAccount = {
  id: string
  name: string
  category: ServiceCategory
  status: ServiceStatus
  owner: string
  accountIdentifier: string
  bitwardenFolder: string
  dashboardUrl: string | null
  version?: string
  notes?: string
  statusNote?: string
  monthlyCostUsd: number | null
  billingCycle: BillingCycle
  launchCritical: boolean
  verifiedAt: string | null
}

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  'Production',
  'Infrastructure',
  'Architecture',
  'Marketing',
  'Finance',
  'Analytics',
  'Legal / Compliance',
]

export const SERVICE_ACCOUNTS: ServiceAccount[] = [
  {
    id: 'asc-pipeline',
    name: 'ASC Pipeline',
    category: 'Architecture',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'Local worker + Endless Tales admin',
    bitwardenFolder: 'Endless Tales / Architecture / ASC Pipeline',
    dashboardUrl: null,
    version: 'v2.3.69',
    notes: 'Canonical story production architecture and local worker path.',
    monthlyCostUsd: 0,
    billingCycle: 'none',
    launchCritical: true,
    verifiedAt: '2026-05-31',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'Infrastructure',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'Endless Tales production project',
    bitwardenFolder: 'Endless Tales / Infrastructure / Supabase',
    dashboardUrl: 'https://supabase.com/dashboard',
    notes: 'Database, auth, storage, and service-role protected admin access.',
    monthlyCostUsd: 0,
    billingCycle: 'monthly',
    launchCritical: true,
    verifiedAt: '2026-05-31',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'Infrastructure',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'bizgojos-projects / drivetimetales',
    bitwardenFolder: 'Endless Tales / Infrastructure / Vercel',
    dashboardUrl: 'https://vercel.com/dashboard',
    notes: 'Production hosting for app.endless-tales.com.',
    monthlyCostUsd: 20,
    billingCycle: 'monthly',
    launchCritical: true,
    verifiedAt: '2026-05-29',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'Finance',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'Endless Tales live payments',
    bitwardenFolder: 'Endless Tales / Finance / Stripe',
    dashboardUrl: 'https://dashboard.stripe.com',
    notes: 'Subscriptions, billing portal, invoices, and webhooks.',
    monthlyCostUsd: null,
    billingCycle: 'usage',
    launchCritical: true,
    verifiedAt: '2026-05-27',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    category: 'Production',
    status: 'paused',
    owner: 'Marc',
    accountIdentifier: 'Endless Tales voice generation',
    bitwardenFolder: 'Endless Tales / Production / ElevenLabs',
    dashboardUrl: 'https://elevenlabs.io/app',
    notes: 'Primary TTS vendor for story voices, Belle B, and personalized audio.',
    statusNote: 'Paused for cost control. Resume before unattended story production.',
    monthlyCostUsd: 315.33,
    billingCycle: 'annual',
    launchCritical: true,
    verifiedAt: '2026-05-20',
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    category: 'Production',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'Endless Tales script generation',
    bitwardenFolder: 'Endless Tales / Production / Anthropic',
    dashboardUrl: 'https://console.anthropic.com',
    notes: 'Story, script, validation, and repair reasoning.',
    monthlyCostUsd: null,
    billingCycle: 'usage',
    launchCritical: true,
    verifiedAt: '2026-05-26',
  },
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'Production',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'Endless Tales image and support tooling',
    bitwardenFolder: 'Endless Tales / Production / OpenAI',
    dashboardUrl: 'https://platform.openai.com',
    notes: 'Cover generation, operational tooling, and support workflows.',
    monthlyCostUsd: null,
    billingCycle: 'usage',
    launchCritical: false,
    verifiedAt: '2026-05-18',
  },
  {
    id: 'google-workspace',
    name: 'Google Workspace',
    category: 'Infrastructure',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'endless-tales.com email/admin',
    bitwardenFolder: 'Endless Tales / Infrastructure / Google Workspace',
    dashboardUrl: 'https://admin.google.com',
    notes: 'Admin email, shared documents, and login identity.',
    monthlyCostUsd: 14,
    billingCycle: 'monthly',
    launchCritical: true,
    verifiedAt: '2026-05-16',
  },
  {
    id: 'godaddy',
    name: 'GoDaddy',
    category: 'Infrastructure',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'endless-tales.com DNS',
    bitwardenFolder: 'Endless Tales / Infrastructure / GoDaddy',
    dashboardUrl: 'https://dcc.godaddy.com',
    notes: 'Domain registration and DNS records for production aliases.',
    monthlyCostUsd: null,
    billingCycle: 'annual',
    launchCritical: true,
    verifiedAt: '2026-04-23',
  },
  {
    id: 'bitwarden',
    name: 'Bitwarden',
    category: 'Legal / Compliance',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'Endless Tales vault',
    bitwardenFolder: 'Endless Tales / Legal Compliance / Bitwarden',
    dashboardUrl: 'https://vault.bitwarden.com',
    notes: 'Credential vault and access-control source of truth.',
    monthlyCostUsd: 0,
    billingCycle: 'none',
    launchCritical: true,
    verifiedAt: '2026-05-30',
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'Architecture',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'drivetimetales repository',
    bitwardenFolder: 'Endless Tales / Architecture / GitHub',
    dashboardUrl: 'https://github.com',
    notes: 'Source control and deployment history.',
    monthlyCostUsd: 0,
    billingCycle: 'monthly',
    launchCritical: true,
    verifiedAt: '2026-05-25',
  },
  {
    id: 'resend',
    name: 'Resend',
    category: 'Infrastructure',
    status: 'pending_setup',
    owner: 'Marc',
    accountIdentifier: 'Endless Tales transactional email',
    bitwardenFolder: 'Endless Tales / Infrastructure / Resend',
    dashboardUrl: 'https://resend.com',
    notes: 'Transactional email provider for notifications and lifecycle messages.',
    statusNote: 'Pending final launch-domain sending verification.',
    monthlyCostUsd: 0,
    billingCycle: 'monthly',
    launchCritical: false,
    verifiedAt: null,
  },
  {
    id: 'mercury',
    name: 'Mercury',
    category: 'Finance',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'Endless Tales business banking',
    bitwardenFolder: 'Endless Tales / Finance / Mercury',
    dashboardUrl: 'https://mercury.com',
    notes: 'Business banking and cash snapshot source.',
    monthlyCostUsd: 0,
    billingCycle: 'none',
    launchCritical: false,
    verifiedAt: '2026-05-14',
  },
  {
    id: 'airtable',
    name: 'Airtable',
    category: 'Marketing',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'Campaign operations base',
    bitwardenFolder: 'Endless Tales / Marketing / Airtable',
    dashboardUrl: 'https://airtable.com',
    notes: 'Campaign planning and polling-based marketing workflow support.',
    monthlyCostUsd: 0,
    billingCycle: 'monthly',
    launchCritical: false,
    verifiedAt: '2026-04-15',
  },
  {
    id: 'meta-business',
    name: 'Meta Business',
    category: 'Marketing',
    status: 'pending_setup',
    owner: 'Marc',
    accountIdentifier: 'Endless Tales ads/social',
    bitwardenFolder: 'Endless Tales / Marketing / Meta Business',
    dashboardUrl: 'https://business.facebook.com',
    notes: 'Facebook and Instagram campaign account.',
    statusNote: 'Pending launch campaign configuration.',
    monthlyCostUsd: null,
    billingCycle: 'usage',
    launchCritical: false,
    verifiedAt: null,
  },
  {
    id: 'google-analytics',
    name: 'Google Analytics',
    category: 'Analytics',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'Endless Tales GA property',
    bitwardenFolder: 'Endless Tales / Analytics / Google Analytics',
    dashboardUrl: 'https://analytics.google.com',
    notes: 'Traffic, landing-page, and source attribution analytics.',
    monthlyCostUsd: 0,
    billingCycle: 'none',
    launchCritical: false,
    verifiedAt: '2026-05-12',
  },
  {
    id: 'vercel-analytics',
    name: 'Vercel Analytics',
    category: 'Analytics',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'drivetimetales analytics',
    bitwardenFolder: 'Endless Tales / Analytics / Vercel Analytics',
    dashboardUrl: 'https://vercel.com/analytics',
    notes: 'Web vitals and production traffic visibility.',
    monthlyCostUsd: 0,
    billingCycle: 'monthly',
    launchCritical: false,
    verifiedAt: '2026-05-03',
  },
  {
    id: 'canva',
    name: 'Canva',
    category: 'Marketing',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'Endless Tales creative assets',
    bitwardenFolder: 'Endless Tales / Marketing / Canva',
    dashboardUrl: 'https://www.canva.com',
    notes: 'Brand creative, launch graphics, and social media assets.',
    monthlyCostUsd: 0,
    billingCycle: 'monthly',
    launchCritical: false,
    verifiedAt: '2026-02-15',
  },
  {
    id: 'tiktok-business',
    name: 'TikTok Business',
    category: 'Marketing',
    status: 'inactive',
    owner: 'Marc',
    accountIdentifier: 'Endless Tales short-form ads',
    bitwardenFolder: 'Endless Tales / Marketing / TikTok Business',
    dashboardUrl: 'https://business.tiktok.com',
    notes: 'Reserved for later short-form acquisition tests.',
    monthlyCostUsd: null,
    billingCycle: 'usage',
    launchCritical: false,
    verifiedAt: null,
  },
  {
    id: 'legal-templates',
    name: 'Legal Templates',
    category: 'Legal / Compliance',
    status: 'active',
    owner: 'Marc',
    accountIdentifier: 'Privacy and terms document source',
    bitwardenFolder: 'Endless Tales / Legal Compliance / Legal Templates',
    dashboardUrl: null,
    notes: 'Policy drafting reference for privacy, terms, and launch compliance.',
    monthlyCostUsd: 0,
    billingCycle: 'none',
    launchCritical: false,
    verifiedAt: '2026-01-20',
  },
  {
    id: 'legacy-openclaw',
    name: 'OpenClaw Legacy Runner',
    category: 'Architecture',
    status: 'cancelled',
    owner: 'Marc',
    accountIdentifier: 'Legacy automation runner',
    bitwardenFolder: 'Endless Tales / Architecture / Legacy Runners',
    dashboardUrl: null,
    notes: 'Retired runner path retained only for historical traceability.',
    statusNote: 'Cancelled. Do not use for current production work.',
    monthlyCostUsd: 0,
    billingCycle: 'none',
    launchCritical: false,
    verifiedAt: '2026-01-05',
  },
]
