ALTER TABLE story_queue_items
  ADD COLUMN IF NOT EXISTS authorized BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS bible TEXT,
  ADD COLUMN IF NOT EXISTS released_to_hal BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS released_to_hal_at TIMESTAMPTZ;
