-- Genre attributes data load — GENRE-ATTRIBUTES-SPEC v1.0
-- Applied 2026-07-23 — data only (DDL applied in 20260723100000)
-- Uses ON CONFLICT(name) DO UPDATE to update existing genre records without slug

INSERT INTO genres (name, listener_contract, pacing_profile, ending_contract, ending_failure_modes, sound_profile, narrator_register, cover_art_guidance, adjacency_group, hard_rules)
VALUES
  ('Mystery',
   'A fair puzzle the listener could have solved.',
   'Methodical; information revealed in layers; tension is intellectual.',
   'THE CLICK — a reveal that logically re-orders everything the listener heard. All clues planted before the reveal. Payoff is retrospective.',
   E'• Emotional resolution without logical solution\n• Reveal depending on information never given\n• Culprit/answer introduced late',
   'Restrained music; stings on reveals only; silence as a clue-beat.',
   'Measured, precise, withholding.',
   'Standard bright rule applies; intrigue via composition, not darkness.',
   'INVESTIGATIVE',
   E'• Solution derivable from planted clues\n• No reveal without prior setup\n• The central question posed in the opening is answered'),
  ('Thriller',
   'Escalating pressure with everything at stake.',
   'A ticking clock; shrinking options; chapters end mid-danger, never at rest.',
   'RELEASE — the accumulated pressure breaks decisively. Dark endings satisfy; quiet endings do not.',
   E'• Tension deflating before the climax\n• Threat resolved off-screen\n• Stakes shrinking at the end instead of paying off',
   'Tighter music ducking; harder stings; percussive beds under chase or pursuit sequences.',
   'Urgent, driving, close.',
   'Standard bright rule applies; energy via subject and angle.',
   'SUSPENSE',
   E'• A clock or closing window exists and is felt\n• The climax happens on-page\n• The ending releases the pressure — through triumph or catastrophe'),
  ('Horror',
   'Dread that gets under the skin and lingers.',
   'Slow accumulation punctuated by spikes; restraint before revelation.',
   'THE LINGER — the immediate ordeal resolves, but one door stays open. Full tidy resolution is a breach in this genre alone.',
   E'• Over-explaining the horror\n• A fully safe "everything is fine" close\n• The threat neutralized so completely nothing lingers',
   'Low end and silence carry the genre; what is NOT heard matters; sparse stings, maximum contrast.',
   'Controlled, intimate, unhurried.',
   'DARK EXCEPTION APPLIES — subject matter legitimately dictates darker palettes. Legibility at thumbnail size still required.',
   'SUSPENSE',
   E'• Dread is earned by restraint, not gore\n• The immediate story question resolves even when the larger dread remains\n• One deliberate open door'),
  ('Comedy',
   'Rhythm, laughter, and order restored.',
   'Timing is the core attribute; setups pay off on a beat; pauses before punchlines are a production requirement, not a script suggestion.',
   'THE LIFT — endings land up: reconciliation, absurdity resolved, the world set right. Warmth is part of the payoff.',
   E'• Ending on a down or neutral beat\n• Final punchline unearned\n• Resolution that abandons the comic premise for sudden seriousness',
   'Silence around punchlines; buoyant beds; stings only as comic punctuation.',
   'Warm, dry, impeccable timing.',
   'Bright rule applies emphatically — light palettes are part of the promise.',
   'LIGHT',
   E'• The ending lands up\n• Punchline beats get breathing room in the mix\n• The comic premise is honored to the last line'),
  ('Western',
   'A moral code tested in a lawless space; a reckoning delivered.',
   'Deliberate; the genre breathes; violence brief and consequential.',
   'THE RECKONING — justice-shaped even when bittersweet. The code is vindicated, the cost acknowledged.',
   E'• Reckoning evaded\n• Moral stakes dissolving into ambiguity with no verdict\n• The code never actually tested',
   'Longer ambient beds (wind, distance, hooves); sparse music; space in the mix mirrors space in the setting.',
   'Grounded, weathered, unhurried.',
   'Bright rule applies naturally — daylight, open country, big sky.',
   'FRONTIER',
   E'• The protagonist''s code is stated or shown early and tested\n• A reckoning occurs\n• Consequences are paid on-page'),
  ('Drama',
   'Truth about people, arrived at through pressure.',
   'Character-led; pressure builds through relationship friction, not external threat.',
   'THE CHANGE — a character is measurably different at the end. The change must cost something.',
   E'• Change asserted but not dramatized\n• Pressure without consequence\n• Emotional resolution that requires no change',
   'Spare music; long spaces; silence carries emotion.',
   'Intimate, present, unhurried.',
   'Standard bright rule applies; authenticity over drama in the image.',
   'LIGHT',
   E'• A character changes\n• The change is dramatized, not narrated\n• The ending earns its emotion'),
  ('Heartwarming',
   'An earned emotional payoff; the ending IS the product.',
   'Gentle build; small moments accumulate; no manufactured jeopardy.',
   'THE GLOW — an emotional payoff earned by everything before it. Sentiment must be built, never asserted.',
   E'• Unearned sentimentality\n• A twist that undercuts the warmth\n• Payoff delivered by coincidence rather than character',
   'Warm beds; generous space; music may swell at the payoff — the one genre where it should.',
   'Warm, sincere, unhurried.',
   'Bright rule applies emphatically — warmth in palette is the promise.',
   'LIGHT',
   E'• The payoff is earned by prior scenes\n• No cynical undercut\n• A listener should finish feeling better than they started'),
  ('Sci-Fi',
   'An idea taken seriously to its human conclusion.',
   'Idea-forward; wonder and unease alternate; exposition earns its place.',
   'THE IMPLICATION LANDS — the ending resolves what the idea MEANS for the people in the story, not merely the plot mechanics.',
   E'• Plot resolved but the idea abandoned\n• Technology as an unexamined magic fix\n• Human cost raised then dropped',
   'Textural beds; clean design for tech elements; room for quiet wonder beats.',
   'Thoughtful, clear, capable of scale.',
   'Bright rule applies; wonder reads better in light than in murk.',
   'SPECULATIVE',
   E'• One central idea, taken seriously\n• The ending answers the idea''s human implication\n• Internal rules of the world stay consistent'),
  ('Historical',
   'A human story made vivid by its historical specificity.',
   'Period-grounded; specific detail earns the listener''s trust.',
   'THE MOMENT LANDS — the historical event or period illuminates the human story; ending may be predetermined by history but the emotional meaning must be earned.',
   E'• Period setting as decoration only\n• Anachronistic characters who sound modern\n• History without consequence',
   'Period-appropriate texture; restrained; specificity over spectacle.',
   'Grounded, clear, respectful of the period.',
   'Standard bright rule applies; historical authenticity in palette and composition.',
   'FRONTIER',
   E'• Historical specificity earns its place\n• The human story is the focus\n• The period''s constraints shape the story')
ON CONFLICT (name) DO UPDATE SET
  listener_contract    = EXCLUDED.listener_contract,
  pacing_profile       = EXCLUDED.pacing_profile,
  ending_contract      = EXCLUDED.ending_contract,
  ending_failure_modes = EXCLUDED.ending_failure_modes,
  sound_profile        = EXCLUDED.sound_profile,
  narrator_register    = EXCLUDED.narrator_register,
  cover_art_guidance   = EXCLUDED.cover_art_guidance,
  adjacency_group      = EXCLUDED.adjacency_group,
  hard_rules           = EXCLUDED.hard_rules;

-- Aliases
UPDATE genres SET alias_of = 'Mystery'    WHERE name = 'Mystery/Crime';
UPDATE genres SET alias_of = 'Mystery'    WHERE name = 'True Crime';

SELECT name, sound_profile IS NOT NULL AS has_spec FROM genres ORDER BY name;
