// app/api/news/no-credits-audio/route.ts
// Returns the pre-generated "sorry, you need credits" audio for a category
// Audio files are generated by /api/admin/generate-no-credits-audio

import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

function getSupabase() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );
}

export async function GET(request: NextRequest) {
  try {
    const supabase = getSupabase();
    const { searchParams } = new URL(request.url);
    const category = searchParams.get('category');

    if (!category) {
      return NextResponse.json({ error: 'category parameter required' }, { status: 400 });
    }

    // Valid categories
    const validCategories = ['state', 'national', 'international', 'business', 'sports', 'science'];
    if (!validCategories.includes(category)) {
      return NextResponse.json({ error: 'Invalid category' }, { status: 400 });
    }

    // Get the pre-generated no-credits audio URL
    const fileName = `no-credits-${category}.mp3`;
    const { data: urlData } = supabase.storage.from('news-audio').getPublicUrl(fileName);
    
    if (!urlData?.publicUrl) {
      return NextResponse.json({ 
        error: 'No-credits audio not found. Admin needs to generate it first.',
        hint: 'POST to /api/admin/generate-no-credits-audio'
      }, { status: 404 });
    }

    return NextResponse.json({ 
      success: true, 
      audioUrl: urlData.publicUrl,
      category
    });

  } catch (error) {
    console.error('[No Credits Audio API] Error:', error);
    return NextResponse.json({ error: 'Failed to get audio' }, { status: 500 });
  }
}
